# Generated by Django 4.2.6 on 2023-10-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kelas', models.CharField(max_length=20)),
                ('nim', models.CharField(max_length=10)),
                ('tgl_lahir', models.DateField()),
            ],
        ),
    ]
