# Generated by Django 4.2.6 on 2023-10-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0002_listmahasiswa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='diskon',
        ),
    ]
