# Generated by Django 4.2.6 on 2023-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0003_rename_completed_todoitem_diskon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=100)),
            ],
        ),
    ]
