# Generated by Django 4.2.6 on 2023-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0004_produkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuahItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buah', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=100)),
            ],
        ),
    ]
