# Generated by Django 4.2.6 on 2023-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0007_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='judul',
            field=models.CharField(default='Judul', max_length=200),
            preserve_default=False,
        ),
    ]
