# Generated by Django 4.2.6 on 2023-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0008_article_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
