# Generated by Django 4.2.6 on 2023-10-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihanapp', '0009_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='matakuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mata_kuliah', models.CharField(max_length=10)),
                ('nama_mata_kuliah', models.CharField(max_length=100)),
                ('sks', models.CharField(max_length=1)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
